/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CountryNameRouteImport } from './routes/$countryName'
import { Route as IndexRouteImport } from './routes/index'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryNameRoute = CountryNameRouteImport.update({
  id: '/$countryName',
  path: '/$countryName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$countryName': typeof CountryNameRoute
  '/favorites': typeof FavoritesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$countryName': typeof CountryNameRoute
  '/favorites': typeof FavoritesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$countryName': typeof CountryNameRoute
  '/favorites': typeof FavoritesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$countryName' | '/favorites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$countryName' | '/favorites'
  id: '__root__' | '/' | '/$countryName' | '/favorites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryNameRoute: typeof CountryNameRoute
  FavoritesRoute: typeof FavoritesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryName': {
      id: '/$countryName'
      path: '/$countryName'
      fullPath: '/$countryName'
      preLoaderRoute: typeof CountryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryNameRoute: CountryNameRoute,
  FavoritesRoute: FavoritesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
